// <auto-generated />
using System;
using JevAsk.Api.Market;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JevAsk.Api.Data.Migrations
{
    [DbContext(typeof(CacheDb))]
    [Migration("20261008020950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("JevAsk.Api.Market.AskedQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Probability")
                        .HasColumnType("REAL");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("JevAsk.Api.Market.CachedSeries", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("BarsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StoredAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Ticker");

                    b.ToTable("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
